blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/hsb3/github-inventory/discussions
    about: Ask questions and discuss ideas with the community
  - name: GitHub CLI Documentation
    url: https://cli.github.com/manual/
    about: Official GitHub CLI documentation for authentication and usage