name: Issue Report
description: Submit a bug report, feature request, or question about GitHub Inventory
labels: []
body:
  - type: textarea
    attributes:
      label: Issue Description
      description: Please describe your issue, bug, feature request, or question.
      placeholder: |
        - What were you trying to do?
        - What happened instead?
        - What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Issue Type
      description: What type of issue are you reporting?
      options:
        - Bug Report
        - Feature Request
        - Question/Help
        - Documentation
      default: 0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce (if applicable)
      description: If reporting a bug, please provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Run command: `ghscan --user username`
        2. See error message: ...
        3. Expected behavior: ...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment Information
      description: Please include version info and system details.
      placeholder: |
        - GitHub Inventory version: (run `ghscan --version` or check `pip show github-inventory`)
        - Python version: (run `python --version`)
        - Operating System: (macOS, Linux, Windows)
        - GitHub CLI version: (run `gh --version`)
        - GitHub CLI auth status: (run `gh auth status`)
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, log output, or configuration files that might be helpful.
      placeholder: |
        - Error messages or stack traces
        - Configuration files (remove sensitive data)
        - Screenshots if relevant
    validations:
      required: false
