name: Branch Protection

on:
  schedule:
    # Run weekly on Sundays at 6 AM UTC to ensure branch protection rules are maintained
    - cron: '0 6 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  protect-main-branch:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'hsb3' # Only run on your repos

    steps:
    - name: Protect main branch
      uses: actions/github-script@v7
      with:
        script: |
          try {
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                checks: [
                  { context: 'test (3.12)' },
                  { context: 'test (3.13)' },
                  { context: 'security' }
                ]
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false,
                require_last_push_approval: false
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: true,
              lock_branch: false,
              allow_fork_syncing: true
            });
            console.log('✅ Branch protection rules updated successfully');
          } catch (error) {
            console.log('⚠️ Failed to update branch protection:', error.message);
            // Don't fail the workflow if branch protection fails
          }
